:sparkles: feat: добавить файлы HTML и CSS для каждой страницы#2
pomazkovanton/liza-alert pull request #10
Opened 2022-05-17 13:11 UTC by Adelina1807

добавить файлы HTML и CSS для каждой страницы

2022-05-17 14:30 UTC, puinka commented
Я в фигме вижу 8 страниц, которые надо сверстать. И хоть 4 из них - вариации результата, думаю, надо делать их отдельными страницами.

2022-05-17 14:32 UTC, puinka commented
И еще я не уверена, что можно файлы называть через нижнее подчеркивание  - это ведь синтаксис модификатора.

2022-05-17 14:36 UTC, puinka commented
Давайте тут сразу сделаем и index.css с импортами

2022-05-17 14:41 UTC, puinka commented
Можно css файлы в index.css импортировать.

2022-05-17 14:41 UTC, pomazkovanton requested changes
- По моему мнению нужно сверстать 8 страниц, это уже потом, кто будет писать React, сделает из нашей верстки SPA.
- В Index.html отсался стандартный title
- Думаю index.html нужно переименовать в lesson-video (мы же часть проекта пишем). Конечно это пока под вопросом. Посмотри что скажет другие.
- Остальные страницы думаю нужно называть исходя из приставки lesson (lesson-test, lesson-succes). Что-то в этом духе. Нужно подумать.
- Нужно сохронять атомарность коммита. И не тащить муссор с собой. У тебя в коммит попали package-look.json и yarn.look. Используй вместо git add . -> git add file1 file2, тогда ненужные файлы не попадут в коммит.

2022-05-17 14:46 UTC, puinka requested changes
Я написала комментарии во вкладке Conversation.

2022-05-17 18:49 UTC, puinka requested changes
Класс! А старые файлы типа test_result можно удалить

2022-05-17 22:49 UTC, pomazkovanton approved these changes

2022-05-17 22:57 UTC, merged

2022-05-18 02:59 UTC, pomazkovanton commented
![](https://github.trello.services/images/mini-trello-icon.png) [(#2 ) Создать HTML и СSS файлы страниц](https://trello.com/c/ijhwHLuz/2-2-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-html-%D0%B8-%D1%81ss-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86)