добавить Css-переменные
pomazkovanton/liza-alert pull request #13
Opened 2022-05-17 14:47 UTC by Afonina-Ola

2022-05-17 14:52 UTC, pomazkovanton requested changes
- Нужно откатится. Удалить последний коммит. Командой git reset HEAD~1. И добавить в коммит только файл c переменными (у тебя потянулись шрифты вместе с переменными)
- Переменные перенести в папку css/vendor/variables.css

2022-05-17 15:32 UTC, Afonina-Ola commented
> * Нужно откатится. Удалить последний коммит. Командой git reset HEAD~1. И добавить в коммит только файл c переменными (у тебя потянулись шрифты вместе с переменными)
> * Переменные перенести в папку css/vendor/variables.css

Git ругается не хочет без Pull принимать. Если делаю Pull, все обновляется. Может такой вариант подойдет:

2022-05-17 15:44 UTC, Afonina-Ola commented
Было много страданий, но в итоге коммит добавляет только то что нужно. Надеюсь все ок.

2022-05-17 16:04 UTC, puinka commented
Еще package-lock.json попал в комит, вроде его не надо.

2022-05-17 23:01 UTC, pomazkovanton reviewed
Да, попал package.json, еще и конфликт. Но переменные очень хорошо сделал, молодец!

2022-05-17 23:01 UTC, merged

2022-05-18 02:59 UTC, pomazkovanton commented
![](https://github.trello.services/images/mini-trello-icon.png) [(#3) Создать CSS переменные](https://trello.com/c/dP9ITyKD/3-3-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-css-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5)