Style/text
pomazkovanton/liza-alert pull request #36
Opened 2022-05-18 20:35 UTC by Adelina1807

Добавить стили для блока text

2022-05-18 20:40 UTC, puinka commented on blocks/text/text.css
> +  font-family: 'Golos';
тут значение "var(--font)". У нас есть файл с переменными (variables.css), используй их. пожалуйста. Переменные нужны, чтоб не менять одно и то же значение по всему проекту ,если дизайнер, например, решит поменять фонт с Golos на Inter.

2022-05-18 20:41 UTC, puinka requested changes
Давай использовать переменные для цветов и названия шрифта (см. файл variables.css)

2022-05-19 00:44 UTC, pomazkovanton requested changes
Не хватает еще одного модификатора для жирного текста. Предлагаю сделать его _type_accent

![изображение](https://user-images.githubusercontent.com/18042030/169178528-14aa0d3b-21d5-4b69-adbc-4fe347efc0d2.png)

2022-05-19 00:44 UTC, pomazkovanton commented on blocks/text/_active/text_active.css
> +.text_active {
Этот модификатор не нужен. Такие стили используются на блоке link #12, он должен указывать на ссылки которые были уже посещены. А у тебя блок текс. Это просто текст, он ссылкой не может быть.

2022-05-19 00:44 UTC, pomazkovanton commented on blocks/text/text.css
> +.text {
У тебя не работает stylelint, и поэтому произвольное форматирование кода. Когда я твои коммиты себе закачиваю, весь код форматируется, что приводит к новым изменениям и лишним коммитам.

2022-05-19 06:37 UTC, puinka requested changes
Еще в index.css надо сделать импорты (я забыла вчера об этом сказать)

2022-05-19 12:47 UTC, merged