fonts Подключить шрифты к проекту #1
pomazkovanton/liza-alert pull request #6
Opened 2022-05-17 11:23 UTC by Zhorayeva

2022-05-17 11:25 UTC, puinka approved these changes

2022-05-17 11:32 UTC, pomazkovanton requested changes
Я оставил два коментария. Посмотри пжл.

2022-05-17 11:32 UTC, pomazkovanton commented on css/vendor/fonts.css
> +	font-family: 'GolosTextWebRegular';
Может просто назовем Golos? А не GolosTextWebRegular?

2022-05-17 11:32 UTC, pomazkovanton commented on css/vendor/fonts.css
> +		url('../../accets/fonts/Golos-Text_Bold.woff2') format('woff2');
Здесь надо строчку с woff2 поднять выше, так как сейчас подключается сначала woff, а если его нет только тогда woff2.

2022-05-17 12:04 UTC, pomazkovanton approved these changes
Ты отлично поработала! Молодец!

2022-05-17 12:05 UTC, merged

2022-05-18 03:00 UTC, pomazkovanton commented
![](https://github.trello.services/images/mini-trello-icon.png) [(#1) Подключить шрифты к проекту](https://trello.com/c/hTsQJxGH/1-1-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-%D1%88%D1%80%D0%B8%D1%84%D1%82%D1%8B-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83)